services:
  - type: web
    name: skyward
    env: python
    buildCommand: |
      # Add Chrome repository
      wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
      echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
      
      # Install Chrome and dependencies
      apt-get update
      apt-get install -y google-chrome-stable xvfb
      
      # Install chromedriver
      CHROME_VERSION=$(google-chrome --version | cut -d " " -f3)
      CHROMEDRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_${CHROME_VERSION%%.*}")
      wget -q "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
      unzip chromedriver_linux64.zip
      mv chromedriver /usr/local/bin/
      chmod +x /usr/local/bin/chromedriver
      
      # Verify installations
      google-chrome --version
      chromedriver --version
      
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DISPLAY
        value: ":99"
    autoDeploy: true